# Page settings

baseURL = "https://zzzmisa.com/"
locale = "en-US"
title = "zzzmisa's homepage"
copyright = "© zzzmisa's homepage"
disableKinds = ["taxonomy", "term", "rss", "sitemap", "404"]
theme = "hugo-theme-doors"

# Site information
[params]
googleTagManager = "GTM-M5SJDZ36"
description = ""
ogimage = "https://zzzmisa.com/images/avatar.png"
twitterSite = "@zzzmisa"

# Project section
[params.projects]

# 一時的に非表示
# [[params.projects.list]]
# title = "ZZZMISA'S BLOG"
# url = "https://blog.zzzmisa.com"
# description = "Technological posts and diaries. Japanese version only."
# image = "images/blog.jpg"
# w = "1233"
# h = "680"

# Subproject section
[params.subprojects]

[[params.subprojects.groups]]
title = "Family-friendly Apps"
divider = true

[[params.subprojects.groups.list]]
title = "Tricky Japanese Seasons Quiz"
url = "https://apps.apple.com/jp/app/id6793947794"
description = "Japan's four seasons, by quiz."
image = "images/tricky-season.png"
w = "900"
h = "600"

[[params.subprojects.groups.list]]
title = "Animal Vision Explorer"
url = "https://apps.apple.com/jp/app/id6787888506"
description = "See through animals' eyes."
image = "images/animal-vision.png"
w = "900"
h = "600"

[[params.subprojects.groups.list]]
title = "ChibiReco"
url = "https://apps.apple.com/jp/app/id6778625773"
description = "Turn your family's voices into sound buttons."
image = "images/chibireco.png"
w = "900"
h = "600"

[[params.subprojects.groups.list]]
title = "Tricky Hiragana Quiz"
url = "https://apps.apple.com/jp/app/id6760300781"
description = "おおかみ or おうかみ? Learn by quizzes"
image = "images/confusing-hiragana.png"
w = "900"
h = "600"

[[params.subprojects.groups]]
title = "Web Projects"
divider = true

[[params.subprojects.groups.list]]
title = "JAPAN GITHUB RANKING"
url = "https://japan-github-ranking.zzzmisa.com/"
description = "Ranking of GitHub repositories written in Japanese."
image = "images/japan-github-ranking.png"
w = "780"
h = "520"

[[params.subprojects.groups.list]]
title = "HUGO THEME DOORS"
url = "https://github.com/zzzmisa/hugo-theme-doors"
description = "Single page theme for links to your works."
image = "images/doors.png"
w = "900"
h = "600"

[[params.subprojects.groups.list]]
title = "CURRYJACK"
url = "https://curryjack.zzzmisa.com/"
description = "Game using Open Data Curry."
image = "https://curryjack.zzzmisa.com/ogimage_en.jpg"
w = "780"
h = "524"

[[params.subprojects.groups.list]]
title = "FEATURED IMAGE MAKER"
url = "https://featured-image-maker.zzzmisa.com/en/"
description = "Generator of simple featured images."
image = "https://featured-image-maker.zzzmisa.com/img/logo.png"
w = "780"
h = "520"

[[params.subprojects.groups.list]]
title = "MISA'S ODEKAKE BLOG"
url = "https://odekake.zzzmisa.com"
description = "My recommended spots around Osaka."
image = "images/odekake.jpg"
w = "960"
h = "540"

# Contact section
[params.contact]
position = "top"
avatar = "images/avatar.png"
name = "MISA / @zzzmisa"
description = "I'm Misa, a software engineer based in Osaka, Japan. You can find my professional background on LinkedIn. This site showcases the apps and web projects I create. These days, I'm focused on building apps that families can enjoy together, with a little learning along the way—inspired by what sparks my child's curiosity. :)"

[[params.contact.links]]
label = "X"
url = "https://x.com/zzzmisa"
icon = "x"

[[params.contact.links]]
label = "LinkedIn"
url = "https://www.linkedin.com/in/zzzmisa"
icon = "linkedin"

[[params.contact.links]]
label = "GitHub"
url = "https://github.com/zzzmisa"
icon = "github"

[[params.contact.links]]
label = "ZZZMISA'S BLOG"
url = "https://blog.zzzmisa.com"
icon = "images/icons/newspaper.svg"

[[params.contact.links]]
label = "Email"
url = "https://docs.google.com/forms/d/e/1FAIpQLSdmZDfWbJXaHeG3EDmlgfXZXdfZw15Ot0gFwtpNbs3yIhTuJA/viewform"
icon = "email"
