# Page settings

baseurl = "https://zzzmisa.com/"
languageCode = "en-us"
title = "zzzmisa's homepage"
copyright = "© zzzmisa's homepage"
googleAnalytics = "UA-88635038-3"
disableKinds = ["taxonomy", "taxonomyTerm"]
publishDir = "docs"
theme = "hugo-theme-doors"

disableRSS = true
disableSitemap = true
disable404 = true

# Site information
[params]
description = ""
ogimage = "https://zzzmisa.com/images/logo.png"

# Project section
[params.projects]

[[params.projects.list]]
title = "zzzmisa's blog"
url = "https://blog.zzzmisa.com"
description = "Technological posts and diaries. Japanese version only."
image = "images/blog.jpg"
w = "960"
h = "540"

[[params.projects.list]]
title = "Misa's Odekake Blog"
url = "https://odekake.zzzmisa.com"
description = "My recommended spots around Osaka."
image = "images/odekake.jpg"
w = "960"
h = "540"

# Subproject section
[params.subprojects]

[[params.subprojects.list]]
title = "Featured Image Maker"
url = "https://featured-image-maker.zzzmisa.com/en/"
description = "Generator of simple featured images."
image = "https://featured-image-maker.zzzmisa.com/img/logo.png"
w = "780"
h = "520"

[[params.subprojects.list]]
title = "Curry Jack"
url = "https://curryjack.zzzmisa.com"
description = "The game made with open data. Japanese version only."
image = "https://curryjack.zzzmisa.com/ogimage.jpg"
w = "780"
h = "524"

[[params.subprojects.list]]
title = "Hugo Theme Doors"
url = "https://themes.gohugo.io/hugo-theme-doors/"
description = "Single page theme for links to your works."
image = "images/doors.png"
w = "900"
h = "600"

# Contact section
[params.contact]
twitter = "https://twitter.com/zzzmisa"
facebook = ""
linkedin = "https://twitter.com/zzzmisa"
github = "https://github.com/zzzmisa"
email = "https://docs.google.com/forms/d/e/1FAIpQLSdmZDfWbJXaHeG3EDmlgfXZXdfZw15Ot0gFwtpNbs3yIhTuJA/viewform"
